apiVersion: v1
kind: ConfigMap
metadata:
  name: mancala-config
  namespace: default
data:
  OMP_NUM_THREADS: "4"
  DEFAULT_DEPTH: "8"
  MOTOR_PORT: "8001"
  CORS_ORIGINS: "http://localhost:30080,http://frontend-svc"
