sonar.projectKey=BARCO_PROYEC-FINAL-INFRA_IA
sonar.organization=barco
sonar.projectName=Mancala Motor Paralelo
sonar.projectVersion=1.0

sonar.sources=motor/src,backend/app,frontend
sonar.tests=motor/tests,backend/tests

sonar.python.version=3.12
sonar.coverage.exclusions=**/tests/**,**/bench/**
